/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pers.ruikai.pwms;

import org.junit.jupiter.api.Test;

import pers.ruikai.pwms.App;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
