/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pers.ruikai.pwms;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
